name: terraform apply
on:
  push:
    branches:
      - main
    paths:
      - terraform/**
  workflow_dispatch:

concurrency:
  group: terraform_apply
  cancel-in-progress: true

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_tvm_bot_webhook_secret: ${{ secrets.TVM_BOT_WEBHOOK_SECRET }}
      TF_VAR_tvm_bot_github_token: ${{ secrets.TVM_BOT_GITHUB_TOKEN }}
      TF_VAR_tvm_bot_repo: tvm
      TF_VAR_tvm_bot_owner: apache
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch' }}
        uses: dflook/terraform-apply@e1c1b7e1d0eed8bda30338e54ff3cd6790a6f35b #v1.25.1
        with:
          var_file: |
            terraform/vars/tvm-ci-prod.auto.tfvars
          workspace: tvm-ci-prod
          path: ./terraform
      - name: Terraform Apply (workflow dispatch)
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' }}
        uses: dflook/terraform-apply@e1c1b7e1d0eed8bda30338e54ff3cd6790a6f35b #v1.25.1
        with:
          var_file: |
            terraform/vars/tvm-ci-prod.auto.tfvars
          workspace: tvm-ci-prod
          path: ./terraform
          auto_approve: true
